version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(docker)"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3
