name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["Build and Publish Docker image"]
    types: 
      - completed
  workflow_dispatch:
      inputs:
        is_manual:
          required: false
          type: boolean
          default: false

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem     

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
  
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i ansible/inventory ansible/playbook.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }} --ssh-common-args='-o StrictHostKeyChecking=no' --extra-vars ansible_user=${{ secrets.ANSIBLE_USER }} --extra-vars registry_username=${{ github.repository_owner }} --extra-vars registry_token=${{ secrets.GITHUB_TOKEN }} --extra-vars image_name=ghcr.io/${{ github.repository }}:master