name: Snyk Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe la dernière version de la CLI Snyk
      - name: Set up Snyk
        uses: snyk/actions/setup@master

      # 3. Authentifie Snyk avec ton token GitHub Secret
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 4. Scan de sécurité (mode debug activé)
      - name: Test for vulnerabilities
        run: DEBUG=* snyk test --severity-threshold=medium
        # Si tu veux tester tous les projets, remplace par :
        # run: DEBUG=* snyk test --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. Envoie le projet vers le dashboard Snyk
      - name: Monitor project in Snyk
        run: snyk monitor
        # Pour tous les projets : snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
