name: Trigger Infra Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - infra

jobs:
  call-infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infra Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          repository: bzhsport-cesi/breizhsport_infra
          event-type: deploy-from-front